---
- name: restart docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    scope: "{{ docker_rootless_mode | ternary('user', 'system') }}"

- name: reset ssh
  ansible.builtin.meta: reset_connection

